# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

upstream fluxmq_amqp_cluster {
    zone fluxmq_amqp_cluster_zone 64k;
    random two least_conn;
    server 172.30.0.201:5682;
    server 172.30.0.202:5682;
    server 172.30.0.203:5682;
}
