# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

upstream fluxmq_http_cluster {
    zone fluxmq_http_cluster_zone 64k;
    random two least_conn;
    server 172.30.0.201:8090;
    server 172.30.0.202:8090;
    server 172.30.0.203:8090;
}
