# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

upstream fluxmq_amqp_cluster {
    least_conn;
    server fluxmq-node1:5682;
    server fluxmq-node2:5683;
    server fluxmq-node3:5684;
}
