# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

upstream mqtt_ws_cluster {
    zone mqtt_ws_cluster_zone 64k;
    random two least_conn;
    server 172.30.0.201:8883;
    server 172.30.0.202:8883;
    server 172.30.0.203:8883;
}
