# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

upstream mqtt_cluster {
    zone mqtt_cluster_zone 64k;
    random two least_conn;
    server 172.30.0.201:1883;
    server 172.30.0.202:1883;
    server 172.30.0.203:1883;
}
