{
 "title": "magistrala",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Allocated Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{}",
     "legendFormat": "{{instance}} - Code {{code}}"
    }
   ]
  },
  {
   "title": "Goroutines instaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "go_goroutines{}", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Things-Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Things Request Count",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "things_api_request_count{}", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Things Latency Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(things_api_request_latency_microseconds, \"quantile\", \"50th percentile\", \"quantile\", \"0.5\"), \"quantile\", \"90th percentile\", \"quantile\", \"0.9\"), \"quantile\", \"99th percentile\", \"quantile\", \"0.99\")",
     "legendFormat": "{{method}} - {{quantile}}"
    }
   ]
  },
  { "title": "Users-Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Users Request Count",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "users_api_request_count{}", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Users Latency Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(users_api_request_latency_microseconds, \"quantile\", \"50th percentile\", \"quantile\", \"0.5\"), \"quantile\", \"90th percentile\", \"quantile\", \"0.9\"), \"quantile\", \"99th percentile\", \"quantile\", \"0.99\")",
     "legendFormat": "{{method}} - {{quantile}}"
    }
   ]
  },
  { "title": "CoAP-Adapter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Coap Adapter Request Count",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coap_adapter_api_request_count{}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "CoAP Latency Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(coap_adapter_api_request_latency_microseconds, \"quantile\", \"50th percentile\", \"quantile\", \"0.5\"), \"quantile\", \"90th percentile\", \"quantile\", \"0.9\"), \"quantile\", \"99th percentile\", \"quantile\", \"0.99\")",
     "legendFormat": "{{method}} - {{quantile}}"
    }
   ]
  },
  { "title": "Web Sockets-Adapter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Web Sockets Request Count",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_adapter_api_request_count{}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "WS Latency Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(http_adapter_api_request_latency_microseconds, \"quantile\", \"50th percentile\", \"quantile\", \"0.5\"), \"quantile\", \"90th percentile\", \"quantile\", \"0.9\"), \"quantile\", \"99th percentile\", \"quantile\", \"0.99\")",
     "legendFormat": "{{method}} - {{quantile}}"
    }
   ]
  },
  { "title": "HTTP-Adapter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "HTTP Adapter Request Count",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_adapter_api_request_count{}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Latency Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(http_adapter_api_request_latency_microseconds, \"quantile\", \"50th percentile\", \"quantile\", \"0.5\"), \"quantile\", \"90th percentile\", \"quantile\", \"0.9\"), \"quantile\", \"99th percentile\", \"quantile\", \"0.99\")",
     "legendFormat": "{{method}} - {{quantile}}"
    }
   ]
  }
 ]
}