FROM golang:1.8-alpine AS builder
WORKDIR /go/src/github.com/mainflux/mainflux
COPY . .
RUN cd cmd/http && CGO_ENABLED=0 GOOS=linux go build -ldflags "-s" -a -installsuffix cgo -o exe

FROM scratch
COPY --from=builder /go/src/github.com/mainflux/mainflux/cmd/http/exe /
EXPOSE 7070
ENTRYPOINT ["/exe"]
