# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0
pkgname: mocks
template: testify
mockname: "{{.InterfaceName}}"
filename: "{{snakecase .InterfaceName}}.go"

template-data:
  boilerplate-file: ./tools/config/boilerplate.txt
  with-expecter: true
packages:
  github.com/absmach/magistrala/pkg/sdk:
    interfaces:
      SDK:
        config:
          dir: "./pkg/sdk/mocks"
          mockname: "SDK"
          filename: "sdk.go"
  github.com/absmach/magistrala/re:
    interfaces:
      Repository:
        config:
          dir: "./re/mocks"
      Service:
        config:  
          dir: "./re/mocks"
      Ticker:
        config:
          dir: "./re/mocks"
  github.com/absmach/magistrala/bootstrap:
    interfaces:
      ConfigRepository:
        config:
          dir: "./bootstrap/mocks"
      ConfigReader:
        config:
          dir: "./bootstrap/mocks"
      Service:
        config:
         dir: "./bootstrap/mocks"
  github.com/absmach/magistrala/consumers/notifiers:
    interfaces:
      Service:
        config:
          dir: "./consumers/notifiers/mocks"
      SubscriptionsRepository:
        config:
          dir: "./consumers/notifiers/mocks"
  github.com/absmach/magistrala/provision:
    interfaces:
      Service:
        config:
          dir: "./provision/mocks"
