# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0
pkgname: mocks
template: testify
mockname: "{{.InterfaceName}}"
filename: "{{snakecase .InterfaceName}}.go"
dir: "{{.InterfaceDirRelative}}/mocks"
force-file-write: true
template-data:
  boilerplate-file: ./tools/config/boilerplate.txt
  with-expecter: true
packages:
  github.com/absmach/magistrala/pkg/sdk:
    interfaces:
      SDK:
        config:
          mockname: "SDK"
          filename: "sdk.go"
  github.com/absmach/magistrala/re:
    interfaces:
      Repository:
      Service:
      Ticker:
      Emailer:
  github.com/absmach/magistrala/bootstrap:
    interfaces:
      ConfigRepository:
      ConfigReader:
      Service:
  github.com/absmach/magistrala/consumers/notifiers:
    interfaces:
      Service:
      SubscriptionsRepository:
  github.com/absmach/magistrala/provision:
    interfaces:
      Service:
  github.com/absmach/magistrala/alarms:
    interfaces:
      Service:
      Repository:  
  github.com/absmach/magistrala/reports:
    interfaces:
      Service:
      Repository: 
  github.com/absmach/magistrala/api/grpc/readers/v1:
    interfaces:
      ReadersServiceClient:
        config:
          dir: "./readers/mocks"
          mockname: "ReadersServiceClient"
          filename: "readers_client.go"
