# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

with-expecter: true
filename: "{{.InterfaceName}}.go"
outpkg: "mocks"
boilerplate-file: "./tools/config/boilerplate.txt"
packages:
  github.com/absmach/magistrala/pkg/sdk:
    interfaces:
      SDK:
        config:
          dir: "./pkg/sdk/mocks"
          mockname: "SDK"
          filename: "sdk.go"
