# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional Vault service for SuperMQ platform.
# Since this is optional, this file is dependent of docker-compose file
# from <project_root>/docker. In order to run these services, execute command:
# docker compose -f docker/docker-compose.yaml -f docker/addons/vault/docker-compose.yaml up
# from project root. Vault default port (8200) is exposed, so you can use Vault CLI tool for
# vault inspection and administration, as well as access the UI.

networks:
  supermq-base-net:
    name: supermq-base-net
    external: true

volumes:
  supermq-vault-volume:


services:
  vault:
    image: hashicorp/vault:1.15.4
    container_name: supermq-vault
    ports:
      - ${SMQ_VAULT_PORT}:8200
    networks:
      - supermq-base-net
    volumes:
      - supermq-vault-volume:/vault/file
      - supermq-vault-volume:/vault/logs
      - ./config.hcl:/vault/config/config.hcl
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      VAULT_ADDR: http://127.0.0.1:${SMQ_VAULT_PORT}
      SMQ_VAULT_PORT: ${SMQ_VAULT_PORT}
      SMQ_VAULT_UNSEAL_KEY_1: ${SMQ_VAULT_UNSEAL_KEY_1}
      SMQ_VAULT_UNSEAL_KEY_2: ${SMQ_VAULT_UNSEAL_KEY_2}
      SMQ_VAULT_UNSEAL_KEY_3: ${SMQ_VAULT_UNSEAL_KEY_3}
    entrypoint: /bin/sh
    command: /entrypoint.sh
    cap_add:
      - IPC_LOCK
