// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: clients/v1/clients.proto

package v1

import (
	v1 "github.com/absmach/supermq/api/grpc/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthnReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthnReq) Reset() {
	*x = AuthnReq{}
	mi := &file_clients_v1_clients_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthnReq) ProtoMessage() {}

func (x *AuthnReq) ProtoReflect() protoreflect.Message {
	mi := &file_clients_v1_clients_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthnReq.ProtoReflect.Descriptor instead.
func (*AuthnReq) Descriptor() ([]byte, []int) {
	return file_clients_v1_clients_proto_rawDescGZIP(), []int{0}
}

func (x *AuthnReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthnRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authenticated bool                   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthnRes) Reset() {
	*x = AuthnRes{}
	mi := &file_clients_v1_clients_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthnRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthnRes) ProtoMessage() {}

func (x *AuthnRes) ProtoReflect() protoreflect.Message {
	mi := &file_clients_v1_clients_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthnRes.ProtoReflect.Descriptor instead.
func (*AuthnRes) Descriptor() ([]byte, []int) {
	return file_clients_v1_clients_proto_rawDescGZIP(), []int{1}
}

func (x *AuthnRes) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *AuthnRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveChannelConnectionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveChannelConnectionsReq) Reset() {
	*x = RemoveChannelConnectionsReq{}
	mi := &file_clients_v1_clients_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveChannelConnectionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveChannelConnectionsReq) ProtoMessage() {}

func (x *RemoveChannelConnectionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_clients_v1_clients_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveChannelConnectionsReq.ProtoReflect.Descriptor instead.
func (*RemoveChannelConnectionsReq) Descriptor() ([]byte, []int) {
	return file_clients_v1_clients_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveChannelConnectionsReq) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type RemoveChannelConnectionsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveChannelConnectionsRes) Reset() {
	*x = RemoveChannelConnectionsRes{}
	mi := &file_clients_v1_clients_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveChannelConnectionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveChannelConnectionsRes) ProtoMessage() {}

func (x *RemoveChannelConnectionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_clients_v1_clients_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveChannelConnectionsRes.ProtoReflect.Descriptor instead.
func (*RemoveChannelConnectionsRes) Descriptor() ([]byte, []int) {
	return file_clients_v1_clients_proto_rawDescGZIP(), []int{3}
}

type UnsetParentGroupFromClientReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentGroupId string                 `protobuf:"bytes,1,opt,name=parent_group_id,json=parentGroupId,proto3" json:"parent_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsetParentGroupFromClientReq) Reset() {
	*x = UnsetParentGroupFromClientReq{}
	mi := &file_clients_v1_clients_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsetParentGroupFromClientReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsetParentGroupFromClientReq) ProtoMessage() {}

func (x *UnsetParentGroupFromClientReq) ProtoReflect() protoreflect.Message {
	mi := &file_clients_v1_clients_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsetParentGroupFromClientReq.ProtoReflect.Descriptor instead.
func (*UnsetParentGroupFromClientReq) Descriptor() ([]byte, []int) {
	return file_clients_v1_clients_proto_rawDescGZIP(), []int{4}
}

func (x *UnsetParentGroupFromClientReq) GetParentGroupId() string {
	if x != nil {
		return x.ParentGroupId
	}
	return ""
}

type UnsetParentGroupFromClientRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsetParentGroupFromClientRes) Reset() {
	*x = UnsetParentGroupFromClientRes{}
	mi := &file_clients_v1_clients_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsetParentGroupFromClientRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsetParentGroupFromClientRes) ProtoMessage() {}

func (x *UnsetParentGroupFromClientRes) ProtoReflect() protoreflect.Message {
	mi := &file_clients_v1_clients_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsetParentGroupFromClientRes.ProtoReflect.Descriptor instead.
func (*UnsetParentGroupFromClientRes) Descriptor() ([]byte, []int) {
	return file_clients_v1_clients_proto_rawDescGZIP(), []int{5}
}

var File_clients_v1_clients_proto protoreflect.FileDescriptor

const file_clients_v1_clients_proto_rawDesc = "" +
	"\n" +
	"\x18clients/v1/clients.proto\x12\n" +
	"clients.v1\x1a\x16common/v1/common.proto\" \n" +
	"\bAuthnReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"@\n" +
	"\bAuthnRes\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"<\n" +
	"\x1bRemoveChannelConnectionsReq\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"\x1d\n" +
	"\x1bRemoveChannelConnectionsRes\"G\n" +
	"\x1dUnsetParentGroupFromClientReq\x12&\n" +
	"\x0fparent_group_id\x18\x01 \x01(\tR\rparentGroupId\"\x1f\n" +
	"\x1dUnsetParentGroupFromClientRes2\xe4\x05\n" +
	"\x0eClientsService\x12<\n" +
	"\fAuthenticate\x12\x14.clients.v1.AuthnReq\x1a\x14.clients.v1.AuthnRes\"\x00\x12N\n" +
	"\x0eRetrieveEntity\x12\x1c.common.v1.RetrieveEntityReq\x1a\x1c.common.v1.RetrieveEntityRes\"\x00\x12T\n" +
	"\x10RetrieveEntities\x12\x1e.common.v1.RetrieveEntitiesReq\x1a\x1e.common.v1.RetrieveEntitiesRes\"\x00\x12N\n" +
	"\x0eAddConnections\x12\x1c.common.v1.AddConnectionsReq\x1a\x1c.common.v1.AddConnectionsRes\"\x00\x12W\n" +
	"\x11RemoveConnections\x12\x1f.common.v1.RemoveConnectionsReq\x1a\x1f.common.v1.RemoveConnectionsRes\"\x00\x12n\n" +
	"\x18RemoveChannelConnections\x12'.clients.v1.RemoveChannelConnectionsReq\x1a'.clients.v1.RemoveChannelConnectionsRes\"\x00\x12t\n" +
	"\x1aUnsetParentGroupFromClient\x12).clients.v1.UnsetParentGroupFromClientReq\x1a).clients.v1.UnsetParentGroupFromClientRes\"\x00\x12_\n" +
	"\x13DeleteDomainClients\x12\".common.v1.DeleteDomainEntitiesReq\x1a\".common.v1.DeleteDomainEntitiesRes\"\x00B0Z.github.com/absmach/supermq/api/grpc/clients/v1b\x06proto3"

var (
	file_clients_v1_clients_proto_rawDescOnce sync.Once
	file_clients_v1_clients_proto_rawDescData []byte
)

func file_clients_v1_clients_proto_rawDescGZIP() []byte {
	file_clients_v1_clients_proto_rawDescOnce.Do(func() {
		file_clients_v1_clients_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clients_v1_clients_proto_rawDesc), len(file_clients_v1_clients_proto_rawDesc)))
	})
	return file_clients_v1_clients_proto_rawDescData
}

var file_clients_v1_clients_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_clients_v1_clients_proto_goTypes = []any{
	(*AuthnReq)(nil),                      // 0: clients.v1.AuthnReq
	(*AuthnRes)(nil),                      // 1: clients.v1.AuthnRes
	(*RemoveChannelConnectionsReq)(nil),   // 2: clients.v1.RemoveChannelConnectionsReq
	(*RemoveChannelConnectionsRes)(nil),   // 3: clients.v1.RemoveChannelConnectionsRes
	(*UnsetParentGroupFromClientReq)(nil), // 4: clients.v1.UnsetParentGroupFromClientReq
	(*UnsetParentGroupFromClientRes)(nil), // 5: clients.v1.UnsetParentGroupFromClientRes
	(*v1.RetrieveEntityReq)(nil),          // 6: common.v1.RetrieveEntityReq
	(*v1.RetrieveEntitiesReq)(nil),        // 7: common.v1.RetrieveEntitiesReq
	(*v1.AddConnectionsReq)(nil),          // 8: common.v1.AddConnectionsReq
	(*v1.RemoveConnectionsReq)(nil),       // 9: common.v1.RemoveConnectionsReq
	(*v1.DeleteDomainEntitiesReq)(nil),    // 10: common.v1.DeleteDomainEntitiesReq
	(*v1.RetrieveEntityRes)(nil),          // 11: common.v1.RetrieveEntityRes
	(*v1.RetrieveEntitiesRes)(nil),        // 12: common.v1.RetrieveEntitiesRes
	(*v1.AddConnectionsRes)(nil),          // 13: common.v1.AddConnectionsRes
	(*v1.RemoveConnectionsRes)(nil),       // 14: common.v1.RemoveConnectionsRes
	(*v1.DeleteDomainEntitiesRes)(nil),    // 15: common.v1.DeleteDomainEntitiesRes
}
var file_clients_v1_clients_proto_depIdxs = []int32{
	0,  // 0: clients.v1.ClientsService.Authenticate:input_type -> clients.v1.AuthnReq
	6,  // 1: clients.v1.ClientsService.RetrieveEntity:input_type -> common.v1.RetrieveEntityReq
	7,  // 2: clients.v1.ClientsService.RetrieveEntities:input_type -> common.v1.RetrieveEntitiesReq
	8,  // 3: clients.v1.ClientsService.AddConnections:input_type -> common.v1.AddConnectionsReq
	9,  // 4: clients.v1.ClientsService.RemoveConnections:input_type -> common.v1.RemoveConnectionsReq
	2,  // 5: clients.v1.ClientsService.RemoveChannelConnections:input_type -> clients.v1.RemoveChannelConnectionsReq
	4,  // 6: clients.v1.ClientsService.UnsetParentGroupFromClient:input_type -> clients.v1.UnsetParentGroupFromClientReq
	10, // 7: clients.v1.ClientsService.DeleteDomainClients:input_type -> common.v1.DeleteDomainEntitiesReq
	1,  // 8: clients.v1.ClientsService.Authenticate:output_type -> clients.v1.AuthnRes
	11, // 9: clients.v1.ClientsService.RetrieveEntity:output_type -> common.v1.RetrieveEntityRes
	12, // 10: clients.v1.ClientsService.RetrieveEntities:output_type -> common.v1.RetrieveEntitiesRes
	13, // 11: clients.v1.ClientsService.AddConnections:output_type -> common.v1.AddConnectionsRes
	14, // 12: clients.v1.ClientsService.RemoveConnections:output_type -> common.v1.RemoveConnectionsRes
	3,  // 13: clients.v1.ClientsService.RemoveChannelConnections:output_type -> clients.v1.RemoveChannelConnectionsRes
	5,  // 14: clients.v1.ClientsService.UnsetParentGroupFromClient:output_type -> clients.v1.UnsetParentGroupFromClientRes
	15, // 15: clients.v1.ClientsService.DeleteDomainClients:output_type -> common.v1.DeleteDomainEntitiesRes
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_clients_v1_clients_proto_init() }
func file_clients_v1_clients_proto_init() {
	if File_clients_v1_clients_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clients_v1_clients_proto_rawDesc), len(file_clients_v1_clients_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clients_v1_clients_proto_goTypes,
		DependencyIndexes: file_clients_v1_clients_proto_depIdxs,
		MessageInfos:      file_clients_v1_clients_proto_msgTypes,
	}.Build()
	File_clients_v1_clients_proto = out.File
	file_clients_v1_clients_proto_goTypes = nil
	file_clients_v1_clients_proto_depIdxs = nil
}
