# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'magistrala'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    follow_redirects: true
    enable_http2: true
    static_configs:
    - targets: 
      - magistrala-things:9000
      - magistrala-users:9002
      - magistrala-http:8008
      - magistrala-ws:8186
      - magistrala-coap:5683
