# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

name: Bug Report
description: File a bug/issue report. Make sure to search to see if an issue already exists for the bug you encountered.
title: "Bug: <title>"
labels: ["bug", "needs-review", "help wanted"]
body:
  - type: textarea
    attributes:
      label: What were you trying to achieve?
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What are the expected results?
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What are the received results?
      description: A concise description of what you received.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: What are the steps to reproduce the issue?
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: In what environment did you encounter the issue?
      description: A concise description of the environment you encountered the issue in.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information you deem important
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
