# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# To listen all messsage broker subjects use default value "alarms.>".
# To subscribe to specific subjects use values starting by "alarms." and
# followed by a subtopic (e.g ["alarms.<domain_id>.c.<channel_id>.sub.topic.x", ...]).
[subscriber]
subjects = ["alarms.>"]

[transformer]
format = "gob"
