# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

ARG BASE_IMAGE=base
FROM chromedp/headless-shell:latest AS base
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

FROM scratch AS scratch-base
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

ARG BASE_IMAGE=base
FROM ${BASE_IMAGE} AS final
ARG SVC
COPY $SVC /exe
ENTRYPOINT ["/exe"]
