###
# This docker-compose file contains optional lora-adapter and lora-redis services
# for the Mainflux platform. Since this services are optional, this file is dependent on the
# docker-compose.yml file from <project_root>/docker/. In order to run these services,
# core services, as well as the network from the core composition, should be already running.
###

version: "3"

networks:
  docker_mainflux-base-net:
    external: true

services:
  lora-redis:
    image: redis:5.0-alpine
    container_name: mainflux-lora-redis
    restart: on-failure
    networks:
      - docker_mainflux-base-net

  lora-adapter:
    image: mainflux/lora:latest
    container_name: mainflux-lora
    restart: on-failure
    environment:
      MF_LORA_ADAPTER_LOG_LEVEL: debug
      MF_THINGS_ES_URL: things-redis:6379
      MF_LORA_ADAPTER_ROUTEMAP_URL: lora-redis:6379
      MF_LORA_ADAPTER_LORA_MESSAGE_URL: tcp://lora.mqtt.mainflux.io:1883
      MF_LORA_ADAPTER_HTTP_PORT: 8187
      MF_NATS_URL: nats://nats:4222
    ports:
      - 8187:8187
    networks:
      - docker_mainflux-base-net
