# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# To listen all messsage broker subjects use default value "w.>".
# To subscribe to specific subjects use values starting by "w." and
# followed by a subtopic (e.g ["w.<channel_id>.sub.topic.x", ...]).
[subjects]
filter = ["w.>"]
