// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewTicker creates a new instance of Ticker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTicker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Ticker {
	mock := &Ticker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Ticker is an autogenerated mock type for the Ticker type
type Ticker struct {
	mock.Mock
}

type Ticker_Expecter struct {
	mock *mock.Mock
}

func (_m *Ticker) EXPECT() *Ticker_Expecter {
	return &Ticker_Expecter{mock: &_m.Mock}
}

// Stop provides a mock function for the type Ticker
func (_mock *Ticker) Stop() {
	_mock.Called()
	return
}

// Ticker_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Ticker_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *Ticker_Expecter) Stop() *Ticker_Stop_Call {
	return &Ticker_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *Ticker_Stop_Call) Run(run func()) *Ticker_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Ticker_Stop_Call) Return() *Ticker_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *Ticker_Stop_Call) RunAndReturn(run func()) *Ticker_Stop_Call {
	_c.Run(run)
	return _c
}

// Tick provides a mock function for the type Ticker
func (_mock *Ticker) Tick() <-chan time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tick")
	}

	var r0 <-chan time.Time
	if returnFunc, ok := ret.Get(0).(func() <-chan time.Time); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan time.Time)
		}
	}
	return r0
}

// Ticker_Tick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tick'
type Ticker_Tick_Call struct {
	*mock.Call
}

// Tick is a helper method to define mock.On call
func (_e *Ticker_Expecter) Tick() *Ticker_Tick_Call {
	return &Ticker_Tick_Call{Call: _e.mock.On("Tick")}
}

func (_c *Ticker_Tick_Call) Run(run func()) *Ticker_Tick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Ticker_Tick_Call) Return(timeCh <-chan time.Time) *Ticker_Tick_Call {
	_c.Call.Return(timeCh)
	return _c
}

func (_c *Ticker_Tick_Call) RunAndReturn(run func() <-chan time.Time) *Ticker_Tick_Call {
	_c.Call.Return(run)
	return _c
}
