# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# This docker-compose file contains optional Vault service for Magistrala platform.
# Since this is optional, this file is dependent of docker-compose file
# from <project_root>/docker. In order to run these services, execute command:
# docker compose -f docker/docker-compose.yaml -f docker/addons/vault/docker-compose.yaml up
# from project root. Vault default port (8200) is exposed, so you can use Vault CLI tool for
# vault inspection and administration, as well as access the UI.

networks:
  magistrala-base-net:

volumes:
  magistrala-vault-volume:

services:
  vault:
    image: hashicorp/vault:1.15.4
    container_name: magistrala-vault
    ports:
      - ${MG_VAULT_PORT}:8200
    networks:
      - magistrala-base-net
    volumes:
      - magistrala-vault-volume:/vault/file
      - magistrala-vault-volume:/vault/logs
      - ./config.hcl:/vault/config/config.hcl
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      VAULT_ADDR: http://127.0.0.1:${MG_VAULT_PORT}
      MG_VAULT_PORT: ${MG_VAULT_PORT}
      MG_VAULT_UNSEAL_KEY_1: ${MG_VAULT_UNSEAL_KEY_1}
      MG_VAULT_UNSEAL_KEY_2: ${MG_VAULT_UNSEAL_KEY_2}
      MG_VAULT_UNSEAL_KEY_3: ${MG_VAULT_UNSEAL_KEY_3}
    entrypoint: /bin/sh
    command: /entrypoint.sh
    cap_add:
      - IPC_LOCK
