{
 "title": "MainfluxDashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "WebSocket adapter request count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ws_adapter_api_request_count{job=\"mainflux\"}[30s])",
     "legendFormat": "ws_count_{{method}}"
    }
   ]
  },
  {
   "title": "WebSocket adapter request latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(ws_adapter_api_request_latency_microseconds{job=\"mainflux\"}[30s])) by (method)",
     "legendFormat": "ws_latency_{{method}}"
    }
   ]
  },
  {
   "title": "HTTP adapter request count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_adapter_api_request_count{job=\"mainflux\"}[30s])",
     "legendFormat": "http_count_{{method}}"
    }
   ]
  },
  {
   "title": "HTTP adapter request latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(http_adapter_api_request_latency_microseconds{job=\"mainflux\"}[30s])) by (method)",
     "legendFormat": "http_latency_{{method}}"
    }
   ]
  },
  {
   "title": "Things request count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(things_api_request_count{job=\"mainflux\"}[30s])",
     "legendFormat": "things_count_{{method}}"
    }
   ]
  },
  {
   "title": "Things request latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(things_api_request_latency_microseconds{job=\"mainflux\"}[30s])) by (method)",
     "legendFormat": "things_latency_{{method}}"
    }
   ]
  },
  {
   "title": "Users request count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(users_api_request_count{job=\"mainflux\"}[30s])",
     "legendFormat": "users_count_{{method}}"
    }
   ]
  },
  {
   "title": "Users request latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(users_api_request_latency_microseconds{job=\"mainflux\"}[30s])) by (method)",
     "legendFormat": "users_latency_{{method}}"
    }
   ]
  }
 ]
}